// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.startupRolloutPrefs.browser.toolbars.bookmarks.2h2020", true);
user_pref("app.normandy.startupRolloutPrefs.network.preload", true);
user_pref("app.normandy.user_id", "19c1ed6e-35bd-4504-93ce-2078cfd7c357");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1612145189);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1612145189);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1612145170);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1612145219);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1612145158);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 104);
user_pref("browser.newtabpage.activity-stream.impressionId", "{dc8fd602-24d6-435f-820d-25086f295c8e}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1612145234458");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1612147050458");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1612145229555");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1612166829555");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1612145162");
user_pref("browser.slowStartup.averageTime", 5368);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20210105180113");
user_pref("browser.startup.homepage_override.mstone", "84.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1612145161);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1612145181313");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "84.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("dom.push.userAgentID", "b8ce2b08f3ad4c5cb9933b1a1074735a");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "84.0.2");
user_pref("extensions.lastPlatformVersion", "84.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_picture_in_picture_overrides", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"a4327578-765a-4fe9-be0a-8710c5f8be78\",\"formautofill@mozilla.org\":\"d48a8490-76fd-43f0-9b59-024f153f4910\",\"screenshots@mozilla.org\":\"9bbee76a-916f-4ea0-ac99-7b3185a43df3\",\"webcompat-reporter@mozilla.org\":\"d487942c-1f5c-4438-aa5b-0716468b7b37\",\"webcompat@mozilla.org\":\"fb229d7f-6c9a-4445-bcac-985e277df74e\",\"default-theme@mozilla.org\":\"561e0385-29c3-4f62-a03f-98f50be5d9f8\",\"google@search.mozilla.org\":\"e94be2db-e934-4c52-bc8b-9b9668ad9390\",\"wikipedia@search.mozilla.org\":\"0648edcd-a889-4413-b3a4-91c355ecabc9\",\"baidu@search.mozilla.org\":\"4d130c6e-864a-482c-84c1-08d0d9e51c94\",\"bing@search.mozilla.org\":\"67bc6f04-3b85-4aab-b279-5ecae239d659\",\"ddg@search.mozilla.org\":\"6f3d027f-47e4-4f9e-81d8-5cfa186b5110\",\"amazondotcn@search.mozilla.org\":\"99f3bddb-458b-43b6-bf47-5fc6f9d8130c\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "dbebccff-802b-4603-9c55-338d11caa508");
user_pref("security.sandbox.plugin.tempDirSuffix", "3694dbd8-2f38-4b61-a802-1eb82b428697");
user_pref("toolkit.startup.last_success", 1612145156);
user_pref("toolkit.telemetry.cachedClientID", "7ee64e6f-7c3f-472e-80df-7b6e96df303c");
user_pref("toolkit.telemetry.previousBuildID", "20210105180113");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
